Update dependencies

diff --git a/.github/workflows/workflow-fail.yml b/.github/workflows/workflow-fail.yml
--- a/.github/workflows/workflow-fail.yml
+++ b/.github/workflows/workflow-fail.yml
@@ -5,8 +5,6 @@ on:
     branches:
       - main
       - release/0.2.0
-    paths:
-      - .github/workflows/workflow-fail.yml
 
 jobs:
   workflow_fail:
@@ -17,5 +15,5 @@ jobs:
         run: |
           sleep 15
           date
-          echo "Fake ERROR" 1>&2
+          echo "Fake ERROR" >&2
           exit 125
